import type { Metadata } from "next";
import "./globals.css";
import Provider from "./_provider";
import "react-loading-skeleton/dist/skeleton.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' cz-shortcut-listen='true'>
      <body cz-shortcut-listen='true' className={` antialiased`}>
        <Provider>{children}</Provider>
        <div id='__next'></div>
      </body>
    </html>
  );
}
